### ISSUE TITLE
left mouse click on TCA icon in toolbar crashes KSP [1.7.3/3.5.7.0]

### ISSUE THREAD

**Issue by yannleretaille** [allista/ThrottleControlledAvionics#75] opened 2019-08-30 13:44 UTC
**Describe the bug**
Seems to happen in all modes, including Space Center & VAB

**To Reproduce**
1. Launch game with TCA installed
2. left click the TCA icon
3. game instantly crashes without warning or producing any log messages

**Log files**
[Player.log](https://github.com/allista/ThrottleControlledAvionics/files/3560089/Player.log)
[KSP.log](https://github.com/allista/ThrottleControlledAvionics/files/3560102/KSP.log)

**Environment:**
 - OS: Linux(Arch) + Steam

**KSP:**
 - Version: 1.7.3
 - Mods:
```
ALCOR
Chatterer
DistantObject
DistantObject-default
EditorExtensionsRedux
EnvironmentalVisualEnhancements
EnvironmentalVisualEnhancements-HR
KerbalEngineerRedux
ProceduralFairings
RemoteTech
SCANsat
Trajectories
Toolbar
ContractConfigurator
ASETAgency
ModuleManager
ClickThroughBlocker
surfacelights
PoodsCalmNebulaSkybox
TextureReplacer
EngineLightRelit
ProceduralParts
VensStylePPTextures
BasicProceduralTextures
KerbalJointReinforcementNext
BetterBurnTime
CommunityTechTree
IndicatorLights
ThrottleControlledAvionics
AT-Utils
ConfigurableContainers-Core
NavballDockAlignIndCE
```

**Comment by allista** [comment] 2019-11-08 11:44
Cannot reproduce on dev build for 1.8.1
Unfortunately, I don't have resources to support older KSP versions, so you'll have to wait for the next release and switch to 1.8.1

**Comment by allista** [comment] 2020-06-08 06:07
Closing as fixed

**Closed by allista** 2020-06-08 06:07 UTC
Labels: bug, cannot reproduce
